### ISSUE TITLE
AzureMsiTokenSource constructor takes IConfigurationRoot

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Identity#11]
The `AzureMsiTokenSource` currently always looks in `configurationRoot["AzureServicesAuthConnectionString"]` for the connection string for the `AzureServiceTokenProvider`. This is problematic for a couple of reasons:

* Putting `IConfigurationRoot` into DI is problematic
* No option to decide at runtime to use a different source for this setting (e.g., inside an executable specification)

**What's wrong with putting `IConfigurationRoot` into DI?**

It pushes us down the route of hiding configuration presumptions in places that are hard to find. For example, the only way to discover that a root configuration setting of `AzureServicesAuthConnectionString` lets you override the default service identity behaviour is to look at the source code for `AzureMsiTokenSource`. (In fact we ended up here after trying to work out what the configuration requirements in a completely different Corvus library were.) Our current view is that it's better for types requiring configuration settings either to define an 'options' class, and to depend on that, or to take those settings during DI setup.

**Options under consideration**

1. Optionally pass the connection string (as a plain `string`) at DI registration time
2. Pass an `IConfiguration` at DI registration time
3. Define an options class

Option 1 pushes the decision of where the setting comes from entirely up to the application, so if you want the existing behaviour, you'd now need to write this:

```csharp
services.AddAzureMsiBasedTokenSource(configurationRoot["AzureServicesAuthConnectionString"]);
```

One thing we like about this is that it's absolutely clear what can be configured here.

With option 2, the specific setting name would remain baked into the code, meaning that you'd now only have to write this"

```csharp
services.AddAzureMsiBasedTokenSource(configurationRoot);
```

The benefit of this is that we get consistency across projects—by choosing the setting name, we remove any possibility of each project arbitrarily doing things its own way. But now we have the flexibility to decide in to plug in different settings, e.g., a test can build an in-memory `IConfiguration` and use that, removing any coupling between environmental settings and test behaviour. (Today, we have some cases of build variables needing to be set in certain ways for tests to work, and it would be good to move away from that.)

The downsides are: it's just as difficult to discover what settings actually exist as before; we still have a library-level dependency on `Microsoft.Extensions.Configuration.Abstractions`, which option 1 removes; requires you to pass an `IConfiguration` even if the information you want to pass wasn't already in that form.

With option 3, we'd have something like this:

```csharp
/// <summary>
/// Configuration settings for <see cref="AzureMsiTokenSource"/>.
/// </summary>
public class AzureMsiOptions
{
    /// <summary>
    /// Gets or sets the connection string to use when obtaining tokens as the service identity.
    /// </summary>
    public string AzureServicesAuthConnectionString { get; set; }
}
```

and we would then have three possibilities. We could pass this in as an optional argument at DI registration time:

```csharp
services.AddAzureMsiBasedTokenSource(configurationRoot.Get<AzureMsiOptions>());
```

We could have this setting picked up through DI, either directly, or using the Options mechanism.

Or we do a hybrid, in which we provide both options as overloads for use during DI setup.

**Comment by mwadams** [comment]
It strikes me that normalizing on options classes would be best.

**Comment by idg10** [comment]
Yes, we (@jesspanni and I) had come to a similar view for the general case. The one thing that makes this possibly different is that the normal use case is to supply no configuration at all. In most of the examples we've been looking at, you tend to be required to supply some configuration to get things working, but in the specific case of Managed Identities there is a clear default behaviour (use the ambient identity) and you only tend to want to overrule it in special cases such as tests.

That's not necessarily a reason to do things differently. An options class would certainly still work here. It's more just that I want to be cautious about defining what we consider "normal" on the basis of a slightly unusual case.

**Comment by mwadams** [comment]
I agree - the thing that is interesting about this is case is that the options are "optional" - but I think that is a perfectly valid situation.

**Comment by jongeorge1** [comment]
I definitely prefer the approach of supplying an options class. The only thing I'd add (and this may be obvious to everyone already) is that it's important to differentiate between optional and mandatory parameters - so as standard I'd say that mandatory parameters should be required by the constructors of these classes, and optional ones not.

If you want to be really explicit about default values, one option would be a static Options.Default member which has the advantage that it makes the default values easily discoverable as client code can easily inspect that instance.
