### ISSUE TITLE
Cache credentials and support invalidation

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Identity#204]
Currently, we can end up looking up credentials from key vault every time credentials are requested. Key vault is slow, so we should try to cache things more.

This will also mean plumbing in cache invalidation. We already have methods applications can call to let us know that they already tried the last set of credentials we gave them, and have found them wanting. However, we don't yet have proper implementations for that.

This should go into v3.0 because we need to validate that the API by which applications let us know that a refresh is require works in practice.

**Comment by idg10** [comment]
Question: does `IMicrosoftRestTokenProviderSource` need an equivalent to `IAccessTokenSource.GetReplacementForFailedAccessTokenAsync` and `IAzureTokenCredentialSource.GetReplacementForFailedTokenCredentialAsync`?

**Comment by HowardvanRooijen** [comment]
Could you implement something like

https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azure-key-vault-proxy/

**Comment by idg10** [comment]
We should definitely explore that as an option.

**Comment by idg10** [comment]
Resolved by #222
